### ISSUE TITLE
Raises IndexError if no match along the specified strand is found

### ISSUE THREAD

**Issue by Prakash2403** [urmi-21/orfipy#7]
You can reproduce the problem by running the following code

```
import orfipy_core
seq = '''GTATCGCTGGAGTCGGGTGATCTCCACGGAGACTCGAGTGGTCTCTTCTTGCCGGGAGCCGTCTTCGCCGGGGTTTCCTCTACCAGACCAAAGGGCTCTAGGACCCTCTTTTTGGCCTGGAAAACCGCCTTACCGAGGTTTCCGCCCCAAGACTTATCGTCCTGGAGCTTTTCCTGAAACTCGGAATCGGCGTGGTTGTACTTGAGGTAAGGATTATCCCCCGCCTCAAGTAGCTTGTTGTATTCGAGATCGTGCTCTCGCGCGACCTCGTCCGCCTTATTGACGGGCTGGCCTTTATCAAGGCCGTTGAAGGGTCCGAGGTATTTGTACCCCGGAACTACTAGACCGCGTTGGTCCTGTTTTTGCTGGTTAGCCTTAGGCCGAGGCGCACCTATGGGCGATGCACAACAGGGTTCCGACGGAGTGGGCAATGCCTCGGGAGATTGGCATTGCGATTCCCAGTGGATGGGCGACCGAGTCATCACCAAGTCCACCCGAACCTGGGTGCTGCCCAGCTACAACAACCACATCTACAAGGAAATCAACTCCACCGGCAACGGACTCAACGGCAGCGCCTACTTTGGATACAGTACTCCCTGGGGATATTTCGACTTTAACCGCTTCCACAGCCACTGGAGCCCCCGAGATTGGCAGCGACTCATCAACAACCACTGGGGCTTCAGACCCAAGGCCATGCACGTCAAAATCTTCAACATCCAAGTCAAAGAAGTCACCACCCAGGACCAGACCACCACCGTCGCCTACTTTGGATACAGTACTCCCTGGGGATATTTCGACTTTAACCGCTTCCAC'''
orfipy_core.orfs(seq, starts=['ATG'])
orfipy_core.orfs(seq, starts=['ATG'], strand='f')
```

The following statement `orfipy_core.orfs(seq, starts=['ATG'])` runs without any errors. However, `orfipy_core.orfs(seq, starts=['ATG'], strand='f')` throws `IndexError`. Posting the stacktrace also
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "orfipy/orfipy_core.pyx", line 28, in orfipy_core.orfs
  File "orfipy/orfipy_core.pyx", line 46, in orfipy_core.orfs
IndexError: list index out of range
```

Kindly look into this. Thanks in advance :)

**Comment by urmi-21** [comment]
Thanks for reporting this @Prakash2403. Looks like an easy fix but I can get to it sometime next month.
A workaround, for now, maybe to modify your code to catch the IndexError exception.

```
try:
    result=orfipy_core.orfs(seq, starts=['ATG'], strand='f')
except IndexError as e:
    result=[]
```
